services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: client_section1
      MYSQL_DATABASE: section_db
      MYSQL_PASSWORD: client_section1
    ports:
      - "3307:3306"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  flask:
    build: .
    container_name: turing-test-tool
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    volumes:
        - ./responses:/app/responses