# Use the official MySQL 8.0 image as the base image
FROM mysql:8.0

# Set the working directory where MySQL will look for initialization scripts
WORKDIR /docker-entrypoint-initdb.d/

# Copy the init.sql script to the initialization directory in the container
COPY scripts/init.sql .

# Expose the default MySQL port
EXPOSE 3306

# Set environment variables for MySQL root password and custom database creation
ENV MYSQL_ROOT_PASSWORD=client_section1
ENV MYSQL_DATABASE=section_db
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=client_section1

# The entrypoint for MySQL is already defined in the base image, so MySQL will initialize 
# with the `init.sql` script placed in `/docker-entrypoint-initdb.d/` automatically.