USE section_db;

CREATE TABLE IF NOT EXISTS clinical_note_sections (
    id INT PRIMARY KEY,
    label VARCHAR(255),
    content TEXT,
    section_type ENUM('real', 'synthetic')
);

INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (1,'History of Present Illness','This is a 79 y/o man who underwent a routine CT scan of the chest on 7/28/16 at \nthe request of his primary care physician. This study showed a 5.7 x 4.3 cm \nirregular mass in the superior segment left lower lobe highly suspicious for \nprimary malignancy. PET scan on 8/30/16 showed:\n\nImpression: \n        1. Abnormal F18 FDG-PET/CT scintigraphy. Abnormal FDG hypermetabolism \n        (SUV max: 19.6) localized to the 6.7 x 4.7 cm left lower lobe mass, \n        concerning for carcinoma.  At least 4 intense surrounding foci of FDG \n        activity within the left peribronchial/hilar region, that measure up to \n        1 cm on PET, SUV max of 8. These are concerning for locoregional \n        metastases. Also mild uptake within nonenlarged right hilar, subcarinal, \n        distal left paratracheal lymph nodes, all subcentimeter in size-these \n        are indeterminant in etiology given size and low grade uptake. \n\n        2. A focal 1.3 cm low-density within the posterior to mid left thyroid \n        lobe, non FDG-avid. Consider correlation with thyroid ultrasound for \n        further evaluation. \n\n        3. Otherwise, no evidence of hypermetabolic foci throughout the neck, \n        abdomen, or pelvis to suggest FDG avid distal spread of metastases in \n        these regions. \n\nCT guided biopsy of the left lower lobe lesion on 8/23/16 was positive  for \npoorly differentiated adenocarcinoma, POSITIVE FOR CK7, TTF-1, NEGATIVE FOR \nCK20, CONSISTENT WITH ADENOCARCINOMA, LUNG PRIMARY. An EBUS was performed on \n10/26/16, the left hilar LN and subcarinal LN were biopsied and found to harbor \nmetastatic adenocarcinoma. MRI brain on 9/26/16 was negative for metastatic \ndisease.\n\nThe patient is now seen for consideration of radiation therapy. He reports that \nthe 20 lb weight loss over the past 3 months was mainly due to poor nutrition as \nhe has been busy taking care of his wife who is very ill. He denies any fevers, \nchills, shortness of breath, hemoptysis, chest pain, abdominal pain, hematuria, \nhematochezia, dyschezia, bone pain, motor weakness, or gait abnormalities. He \ndoes report an occasional cough, but productive only of clear sputum.','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (2,'Identification','Mr. James is a 79 year old male with T2bN2M0 adenocarcinoma of the left lower lobe presenting for discussion regarding radiation therapy.','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (3,'Review of Systems','Fatigue: No\nWeight Loss: 20 lbs over the past 3 months (but reports this is due to not \neating since he is taking care of his sick wife)\nHeadaches: NO\nWeakness: NO\nShortness of Breath: No\nChest Pain: No\nCough: No\nFevers/Chills: No\nDifficulty Swallowing: No\nPainful Swallowing: No\nVoice Changes: No\nDiplopia/Blurry Vision: No\nNausea  NO\nVomiting  NO\nAppetite: Moderate\nPO Intake:  Tolerating PO intake','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (4,'RAD/ONC-CONSULT','Site: Massachusetts\nDate: 10/11/2020	Author: Dr. Norris','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (5,'Patient Info','Mr. Yancey is a 46 y/o Native American male who presented to Urology with elevated PSA of 19.69 drawn on 03/03/2020. He underwent a TRUS biopsy with pathology on Apr 30, 2020 showing Gleason score 6(3+3). He last had colonoscopy on 2019-08-06. Diagnosis: T2bN0M1c, very high prostate cancer. The patient is now referred for evaluation for definitive radiation therapy.','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (6,'Physical Exam','TEMP: 99.54 F\nPULSE: 109\nRESP: 16\nBP: 187/120\nPAIN: 0\nWT: 190 lbs\nKPS: 90\nECOG: ECOG 1','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (7,'Past Medical History','1: Coronary arteriosclerosis\n2: Dermatophytosis\n3: GERD\n4: Reactive airways dysfunction syndrome\n5: Depression\n6: Malignant Neoplasm of the Prostate\n7: Elevated PSA\n8: Dizziness\n9: Coronary Artery Disease\n10: Raised prostate specific antigen\n11: Cortical senile cataract','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (8,'Medications','1) CHOLECALCIFEROL (VIT D3) 1,000UNIT TAB TAKE FOUR TABLETS BY MOUTH ONCE DAILY\n2) SIMVASTATIN TAB 20 MG TAKE ONE-HALF TABLET BY MOUTH\n3) BUPROPION HCL 75MG TAB\n4) DOCUSATE NA 50MG/SENNOSIDES 8.6MG TAB\n5) NITROGLYCERIN TAB SL 0.4 MG DISSOLVE ONE TABLET\n6) LISINOPRIL 40MG TAB TAKE ONE TABLET BY MOUTH EVERY DAY FOR BLOOD PRESSURE\n7) FERROUS SULFATE 325MG TAB TAKE ONE TABLET BY MOUTH THREE TIMES A DAY\n8) METOPROLOL SUCCINATE 50MG SA TAB TAKE ONE-HALF TABLET BY MOUTH EVERY DAY','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (9,'Allergies','amoxicillin','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (10,'Social History','Denies tobacco use. Used to drink 4-5 beers per week, has since quit.','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (11,'Family History','Aunt had ovarian ca, uncle had head and neck ca','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (12,'Cancer Treatment History','Radiation:\nChemotherapy:\nHormone Therapy:','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (13,'Assessment and Plan','1. Stage T2bN0M1c prostate cancer\n2. Gleason score Gleason score 6(3+3)\n3. PSA 19.69\n4. Will proceed with radiation therapy planning\n5. Dose: 7200 cGy / 40 fractions','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (14,'LOCAL TITLE','STANDARD TITLE: RADIATION ONCOLOGY CONSULT\nDATE OF NOTE: 2022-03-27\nENTRY DATE: 2022-03-27\nAUTHOR: Dr. Parker\nEXP COSIGNER: Dr. Matthews\nURGENCY STATUS: COMPLETED','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (15,'Patient Information','Hensley, William is a 43 year old male with a history of recently diagnosed very high prostate cancer...','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (16,'Physical Exam','TEMP PULSE RESP BP PAIN WT\n98.04 F 86 12 110/71 1 243 lbs\nKPS: 70\nECOG: ECOG of 3','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (17,'Past Medical/Surgical History','Glaucoma suspect, Coronary arteriosclerosis, Disorder of refraction, Loss of sense of smell...','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (18,'Active Outpatient Medications','1) ASPIRIN 81MG EC TAB TAKE ONE TABLET BY MOUTH ONCE DAILY\n2) SIMVASTATIN TAB 20 MG TAKE ONE-HALF TABLET BY MOUTH...','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (19,'Allergies','ibuprofen','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (20,'Imaging Results','CT abdomen and pelvis on 2021-08-25: No evidence of metastatic disease in the abdomen or pelvis\nMRI abdomen and pelvis on 2021-11-27...','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (21,'Social History','tobacco: Currently smoking, 1ppd x 48 years.\nalcohol: used to drink 1-3 beers per week, has since quit.','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (22,'Family History','No family history of cancer','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (23,'Cancer Treatments','Radiation: \nChemotherapy: \nHormone Therapy: ','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (24,'Treatment Recommendation','For 43 year old male with very high risk prostate cancer, recommend definitive radiation therapy. Will treat to 6480 cGy in 36 fractions using IMRT/IGRT...','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (25,'Signatures','/es/ Dr. Parker\nResident\nSigned: 2022-03-27','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (26,'Receipt Acknowledged By','2022-03-27 /es/ Dr. Matthews STAFF PHYSICIAN,RADIATION ONCO','synthetic');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (27,'Diagnosis','1.4 cm RUL nodule, presumed NSCLC\nStage: cT1b N0 Mx (PET Pending), Stage IA2\nPrognostic factors: prior smoker, 1.5 ppd x 14 years, quit 1980','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (28,'Prior Radiation','denies','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (29,'History of Connective Tissue Diseases','denies','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (30,'History of Implanted Cardiac Device','denies','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (31,'HPI','Unnamed is a 75yo MALE with history of aortic insufficiency status post aortic valve root repair with bioprosthetic valve, with a growing RUL nodule, now 1.4 cm, concerning for NSCLC, cT1b N0 Mx (PET Pending), Stage IA2...','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (32,'CT Chest 3/8/24 Impression','Enlarging right upper lobe nodule which has been present since 2020, but shows further increase in size compared with the 9/8/2023 exam. Findings concerning for very slow growing neoplasm. Please see the REPORT for the complete list of findings.','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (33,'Review of Systems','12 point ROS reviewed and negative except and noted in HPI.','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (34,'PMH','ACTIVE PROBLEM\nHistory of male erectile disorder\nAcute Venous Embolism and Thrombosi\nLong Term (current) use of Anticoag...','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (35,'PSH','Surgery - Principal Procedures:\n1. LAPAROSCOPIC BILATERAL INGUINAL HERNIA REPAIR on AUG 21,2018@08:00\n2. TEE on JUL 7,2020...','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (36,'Medications','Active Outpatient Medications:\nMETOPROLOL SUCCINATE 25MG SA TAB\nTRAZODONE HCL 100MG TAB\nDOCUSATE NA 100MG CAP...','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (37,'Medication Reconciliation Statement','During the course of this encounter the patient reviewed his current medications as they appear in CPRS, discrepancies were reconciled, and changes were documented and discussed with the patient.','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (38,'Allergies','Patient has answered NKA','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (39,'Social History','Smoking: 1.5 ppd x 14 years, quit 1980\nMarital Status: MARRIED','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (40,'Family History','No family history of lung cancer','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (41,'Physical Exam','Date              Vital             Measurement      Qualifiers\n03/22/2024 12:56  Temp F (C)        98 (36.7)        Oral\n   \"        \"     Pulse             63\n   \"        \"     Respir            16               Spontaneous\n   \"        \"     BP                101/56           R Arm, Sitting, Adult\n                                                     Cuff, Cuff-Automated\n   \"        \"     Ht in (cm)        76 (193.04)      Actual\n   \"        \"     Wt lbs (kg)[BMI]  213.2 (96.71)[26]Actual, Standing Weight\n   \"        \"     C/G in (cm)       Unavailable\n   \"        \"     Pain              0\n   \"        \"     POx (L/Min)(%)    97               Room Air\nGeneral: Well appearing Male, no acute distress\nHEENT: No scleral icterus\nNeck: No palpable lymphadenopathy\nCardiovascular: Warm well perfused extremities\nPulmonary: Respirations non-labored\nAbd: Soft, nontender, nondistended\nMusculoskeletal: No lower extremity edema\nPsych: Normal affect\nNeuro: Alert, awake, oriented x 3. Moves all extremities spontaneously.\n ','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (42,'Labs','CBC - NONE FOUND\nCHEM 8 - NONE FOUND\nLIVER PANEL - NONE FOUND','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (43,'Path','personally reviewed and described in HPI','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (44,'Imaging','personally reviewed and described in HPI\nCT Chest 3/8/24\nFindings: Previously noted right upper lobe nodule definitely increased...','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (45,'Assessment and Plan','Unnamed is a 75yo MALE with history of aortic insufficiency status post aortic valve root repair with bioprosthetic valve, with a growing RUL nodule, now 1.4 cm, concerning for NSCLC, cT1b N0 Mx (PET Pending), Stage IA2...','real');
INSERT INTO `clinical_note_sections` (`id`,`label`,`content`,`section_type`) VALUES (46,'Pain Management','n/a; no complaints of cancer related pain','real');
